### ISSUE TITLE
mqtt example gives error "from go2_webrtc import Go2Connection, RTC_TOPIC ModuleNotFoundError: No module named 'go2_webrtc'"

### ISSUE THREAD

**Issue by peterhuisman** [tfoldi/go2-webrtc#16]
I am trying to run the mqtt example to see if I can exchange commands to the Go2 EDU dog over MQTT.
When I run the go2_mqtt.py example, I get the error "
from go2_webrtc import Go2Connection, RTC_TOPIC
ModuleNotFoundError: No module named 'go2_webrtc'
"
which I don't understand, as module go2_webrtc is available in the source code...

**Comment by tfoldi** [comment]
from which directory do you start the mqtt example?

you can also try a `pip install -e .` from the python folder

**Comment by peterhuisman** [comment]
Hello tfoldi...

Sry, beginners error.
Thanks for pointing this out.
Item can be closed.
