### ISSUE TITLE
Can Not control the robot

### ISSUE THREAD

**Issue by RayYoh** [tfoldi/go2-webrtc#6]
Hi, authors, thanks for your great work. I have tried this code and from the browser, the robot can be connected (didn't use token). But when I executed the command, the robot didn't move. Do I need to run something else?

**Comment by tfoldi** [comment]
what did you try to execute? can you share the error messages from your developer console?

**Comment by RayYoh** [comment]
> what did you try to execute? can you share the error messages from your developer console?

I just execute the move command. Actually, no error occurred, the console shows connected. 
After I click connect button several times, it works just about 1 mins and during this time I can see the video stream, then can not control the robot and video stream disappeared.

**Comment by RayYoh** [comment]
> > what did you try to execute? can you share the error messages from your developer console?
> 
> I just execute the move command. Actually, no error occurred, the console shows connected. After I click connect button several times, it works just about 1 mins and during this time I can see the video stream, then can not control the robot and video stream disappeared.

Ahieved that just change the IP from 0.0.0.0 to localhost IP.
