### ISSUE TITLE
confirm the current capability with this repo

### ISSUE THREAD

**Issue by hhung516** [tfoldi/go2-webrtc#7]
Hi guys, thank you so much for making this available for Go2 owners!!! I'm thinking about getting the Air version to fiddle around, but would like to ask a few questions prior to ordering.

First question is about the controller bundle, Air with the controller is about $250 US dollars more than the Air alone. Is the controller a must-have? Can I use a wireless joystick/gamepad with a tablet to achieve the same thing?

Second question, with this repo + official Go2 SDK, what can and cannot be done on the Go2 Air?

Last question, I've seen a tiny tracker in one of the videos which allows Go2 to closely follow the owner. My understanding is this tracker/feature isn't compatible with Go2 Air, correct? What's the advantage of having this tracker? And is it possible to make a poor man's version of the tracker using something like UWB/BLE beacons or wireless occupancy sensors?

**Comment by tfoldi** [comment]
Hi @hhung516, yes, joystick support is in https://github.com/tfoldi/go2-webrtc/blob/master/python/examples/joystick/go2_joystick.py - you can try it out and let me know if you face any issues.

there is a different repo that provides many other things: https://github.com/abizovnuralem/go2_ros2_sdk/ 

On the other questions, I suggest you ask the guys on the roboverse discord server: https://discord.gg/KVuEgFaN
